---
  - name: Install and configure tomcat
    hosts: servers 
    gather_facts: true
    become: yes
    vars:
      req_tomcat_ver: "{{tomcatversion}}"
      req_port: "{{tomcatport}}"
      tomcat_url: https://archive.apache.org/dist/tomcat/tomcat-{{req_tomcat_ver.split('.')[0]}}/v{{req_tomcat_ver}}/bin/apache-tomcat-{{req_tomcat_ver}}.tar.gz
    tasks:

      - name: add vault file
        no_log: True
        ansible.builtin.include_vars:
          file: password.yml

      - name: updating repos
        include_role:
          name: repo-update

      - name: intsalling java
        include_role:
          name: install-java
      
      - name: downloading required tomcat
        get_url:
          url: "{{ tomcat_url }}"
          dest: /usr/local

      - name: extracting tomcat file
        unarchive:
          src: "/usr/local/apache-tomcat-{{req_tomcat_ver}}.tar.gz"
          dest: "/usr/local"
          remote_src: yes

      - name: copy the files
        copy:
          src: tomcatusers.xml
          dest: /usr/local/apache-tomcat-{{req_tomcat_ver}}/conf/tomcat-users.xml
      
      - name: replace admin password
        no_log: True
        lineinfile:
          path: /usr/local/apache-tomcat-{{req_tomcat_ver}}/conf/tomcat-users.xml
          regexp: "<user username='admin' password='dummy' roles='admin-gui'/>"
          line: "        <user username='admin' password='{{password}}' roles='admin-gui'/>"
          remote_src: yes

      - name: replace manager password
        no_log: True
        lineinfile:
          path: /usr/local/apache-tomcat-{{req_tomcat_ver}}/conf/tomcat-users.xml
          regexp: "<user username='admin' password='dummy' roles='manager-gui'/>"
          line: "        <user username='admin' password='{{password}}' roles='manager-gui'/>"
          remote_src: yes

      - name: change port no
        lineinfile:
          path: /usr/local/apache-tomcat-{{req_tomcat_ver}}/conf/server.xml
          regexp: '<Connector port="8080" protocol="HTTP/1.1"'
          line: ' <Connector port="{{req_port}}" protocol="HTTP/1.1"'
          remote_src: yes

      - name: copy the context file
        copy:
          src: context.xml
          dest: /usr/local/apache-tomcat-{{req_tomcat_ver}}/webapps/manager/META-INF

      - name: download war file
        git:
          repo: https://github.com/tusharmathur08/ansiblewar.git
          dest: /tmp/ansible-webapp_{{hostname.name}}/

      - name: copy the war file
        copy:
          src: /tmp/ansible-webapp_{{hostname.name}}/sample_{{hostname.name}}/
          dest: /usr/local/apache-tomcat-{{req_tomcat_ver}}/webapps/
          remote_src: yes

      - name: starting tomcat
        shell: /usr/local/apache-tomcat-{{req_tomcat_ver}}/bin/shutdown.sh && nohup /usr/local/apache-tomcat-{{req_tomcat_ver}}/bin/startup.sh
